#!/bin/sh
# Build the site and validate its links. CI runs this same script, so the
# ignore lists below are the only copy.
set -e

bundle exec jekyll build --drafts

# Sites that reject the proofer rather than serving a bad link:
#   linkedin.com          403s all non-browser traffic
#   snapl, PLSummit, ve0x10.in, nebelwelt.net, roopsha's homepage
#                         reachable in a browser, unreachable from CI
bundle exec htmlproofer ./_site \
  --ignore-status-codes "403" \
  --ignore-urls "/https://www.linkedin.com/,https://snapl.cs.berkeley.edu/2017/index.html,https://pl.cs.uchicago.edu/PLSummit/2024/,ve0x10.in,http://www.nebelwelt.net/,/https://www.cs.purdue.edu/homes/roopsha//" \
  --log-level :debug
