name: Lighthouse Performance
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lighthouse-desktop:
    name: Lighthouse Audit (Desktop)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build --drafts

      - name: Audit with Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: .github/lighthouse/lighthouserc.json
          uploadArtifacts: true
          artifactName: lighthouse-results-desktop

  lighthouse-mobile:
    name: Lighthouse Audit (Mobile)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build site
        run: bundle exec jekyll build --drafts

      - name: Audit with Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          configPath: .github/lighthouse/lighthouserc-mobile.json
          uploadArtifacts: true
          artifactName: lighthouse-results-mobile
